### ISSUE TITLE
Require() Function Malfunction 

### ISSUE THREAD

**Issue by erhanyasar** [marcuswestin/require#12]
Even if I install `require()` with npm both globally and locally, it doesn't seem getting familiarize with it. Even after `npm install` with `requirejs` and `require.js`, it still lacks `require() function`. After adding `require.js` or `common.js` as a script via index.html, it produce some other errors again which make me think not being not recovered well because of prior one again.

It was almost the first time I got the situation with [indexedDBShim/issue#260](https://github.com/axemclion/IndexedDBShim/issues/260) and now with another [Stackoverflow](http://stackoverflow.com/questions/42779721/is-there-any-uptodate-possible-way-to-transform-pdf-docx-into-text-via-javascrip) question's snippet as demonstration and here is an [another question](http://stackoverflow.com/questions/42791660/consequently-uncaught-referenceerror-require-is-not-defined) with directly related this issue.

**Comment by erhanyasar** [comment]
I know it's because I'm trying to use `node.js` in the browser (client-side) as a way to work around hence, using browserify does not overcome async functions other than `require`. Even in the [community](http://www.stackoverflow.com) people repeats there are lots of answers for that but obviously not! I'm still working on and will comment here if I get an answer even closing the issue now.

**Comment by ghost** [comment]
could you solved this problem? have the same here

**Comment by erhanyasar** [comment]
@AAhrit use [browserify](https://github.com/substack/browserify-website) and let me know if I can help more.
